#define NUMBER_OF_TOKENS 256

struct Token {
  char code[10];
  char token[10];
};

struct Token TOKENS[] = {
    {.code = "00", .token = "NOP"},       {.code = "01", .token = "LXI B"},
    {.code = "02", .token = "STAX B"},    {.code = "03", .token = "INX B"},
    {.code = "04", .token = "INR B"},     {.code = "05", .token = "DCR B"},
    {.code = "06", .token = "MVI B"},  {.code = "07", .token = "RLC"},
    {.code = "08", .token = "*NOP"},      {.code = "09", .token = "DAD B"},
    {.code = "0A", .token = "LDAX B"},    {.code = "0B", .token = "DCX B"},
    {.code = "0C", .token = "INR C"},     {.code = "0D", .token = "DCR C"},
    {.code = "0E", .token = "MVI C"},  {.code = "0F", .token = "RRC"},
    {.code = "10", .token = "*NOP"},     {.code = "11", .token = "LXI D"},
    {.code = "12", .token = "STAX D"},   {.code = "13", .token = "INX D"},
    {.code = "14", .token = "INR D"},    {.code = "15", .token = "DCR D"},
    {.code = "16", .token = "MVI D"}, {.code = "17", .token = "RAL"},
    {.code = "18", .token = "*NOP"},     {.code = "19", .token = "DAD D"},
    {.code = "1A", .token = "LDAX D"},   {.code = "1B", .token = "DCX D"},
    {.code = "1C", .token = "INR E"},    {.code = "1D", .token = "DCR E"},
    {.code = "1E", .token = "MVI E"}, {.code = "1F", .token = "RAR"},
    {.code = "20", .token = "*NOP"},     {.code = "21", .token = "LXI H"},
    {.code = "22", .token = "SHLD"}, {.code = "23", .token = "INX H"},
    {.code = "24", .token = "INR H"},    {.code = "25", .token = "DCR H"},
    {.code = "26", .token = "MVI H"}, {.code = "27", .token = "DAA"},
    {.code = "28", .token = "*NOP"},     {.code = "29", .token = "DAD H"},
    {.code = "2A", .token = "LHLD"}, {.code = "2B", .token = "DCX H"},
    {.code = "2C", .token = "INR L"},    {.code = "2D", .token = "DCR L"},
    {.code = "2E", .token = "MVI L"}, {.code = "2F", .token = "CMA"},
    {.code = "30", .token = "*NOP"},     {.code = "31", .token = "LXI SP"},
    {.code = "32", .token = "STA"},  {.code = "33", .token = "INX SP"},
    {.code = "34", .token = "INR M"},    {.code = "35", .token = "DCR M"},
    {.code = "36", .token = "MVI M"}, {.code = "37", .token = "STC"},
    {.code = "38", .token = "*NOP"},     {.code = "39", .token = "DAD SP"},
    {.code = "3A", .token = "LDA"},  {.code = "3B", .token = "DCX SP"},
    {.code = "3C", .token = "INR A"},    {.code = "3D", .token = "DCR A"},
    {.code = "3E", .token = "MVI A"}, {.code = "3F", .token = "CMC"},
    {.code = "40", .token = "MOV B,B"},  {.code = "41", .token = "MOV B,C"},
    {.code = "42", .token = "MOV B,D"},  {.code = "43", .token = "MOV B,E"},
    {.code = "44", .token = "MOV B,H"},  {.code = "45", .token = "MOV B,L"},
    {.code = "46", .token = "MOV B,M"},  {.code = "47", .token = "MOV B,A"},
    {.code = "48", .token = "MOV C,B"},  {.code = "49", .token = "MOV C,C"},
    {.code = "4A", .token = "MOV C,D"},  {.code = "4B", .token = "MOV C,E"},
    {.code = "4C", .token = "MOV C,H"},  {.code = "4D", .token = "MOV C,L"},
    {.code = "4E", .token = "MOV C,M"},  {.code = "4F", .token = "MOV C,A"},
    {.code = "50", .token = "MOV D,B"},  {.code = "51", .token = "MOV D,C"},
    {.code = "52", .token = "MOV D,D"},  {.code = "53", .token = "MOV D,E"},
    {.code = "54", .token = "MOV D,H"},  {.code = "55", .token = "MOV D,L"},
    {.code = "56", .token = "MOV D,M"},  {.code = "57", .token = "MOV D,A"},
    {.code = "58", .token = "MOV E,B"},  {.code = "59", .token = "MOV E,C"},
    {.code = "5A", .token = "MOV E,D"},  {.code = "5B", .token = "MOV E,E"},
    {.code = "5C", .token = "MOV E,H"},  {.code = "5D", .token = "MOV E,L"},
    {.code = "5E", .token = "MOV E,M"},  {.code = "5F", .token = "MOV E,A"},
    {.code = "60", .token = "MOV H,B"},  {.code = "61", .token = "MOV H,C"},
    {.code = "62", .token = "MOV H,D"},  {.code = "63", .token = "MOV H,E"},
    {.code = "64", .token = "MOV H,H"},  {.code = "65", .token = "MOV H,L"},
    {.code = "66", .token = "MOV H,M"},  {.code = "67", .token = "MOV H,A"},
    {.code = "68", .token = "MOV L,B"},  {.code = "69", .token = "MOV L,C"},
    {.code = "6A", .token = "MOV L,D"},  {.code = "6B", .token = "MOV L,E"},
    {.code = "6C", .token = "MOV L,H"},  {.code = "6D", .token = "MOV L,L"},
    {.code = "6E", .token = "MOV L,M"},  {.code = "6F", .token = "MOV L,A"},
    {.code = "70", .token = "MOV M,B"},  {.code = "71", .token = "MOV M,C"},
    {.code = "72", .token = "MOV M,D"},  {.code = "73", .token = "MOV M,E"},
    {.code = "74", .token = "MOV M,H"},  {.code = "75", .token = "MOV M,L"},
    {.code = "76", .token = "HLT"},      {.code = "77", .token = "MOV M,A"},
    {.code = "78", .token = "MOV A,B"},  {.code = "79", .token = "MOV A,C"},
    {.code = "7A", .token = "MOV A,D"},  {.code = "7B", .token = "MOV A,E"},
    {.code = "7C", .token = "MOV A,H"},  {.code = "7D", .token = "MOV A,L"},
    {.code = "7E", .token = "MOV A,M"},  {.code = "7F", .token = "MOV A,A"},
    {.code = "80", .token = "ADD B"},    {.code = "81", .token = "ADD C"},
    {.code = "82", .token = "ADD D"},    {.code = "83", .token = "ADD E"},
    {.code = "84", .token = "ADD H"},    {.code = "85", .token = "ADD L"},
    {.code = "86", .token = "ADD M"},    {.code = "87", .token = "ADD A"},
    {.code = "88", .token = "ADC B"},    {.code = "89", .token = "ADC C"},
    {.code = "8A", .token = "ADC D"},    {.code = "8B", .token = "ADC E"},
    {.code = "8C", .token = "ADC H"},    {.code = "8D", .token = "ADC L"},
    {.code = "8E", .token = "ADC M"},    {.code = "8F", .token = "ADC A"},
    {.code = "90", .token = "SUB B"},    {.code = "91", .token = "SUB C"},
    {.code = "92", .token = "SUB D"},    {.code = "93", .token = "SUB E"},
    {.code = "94", .token = "SUB H"},    {.code = "95", .token = "SUB L"},
    {.code = "96", .token = "SUB M"},    {.code = "97", .token = "SUB A"},
    {.code = "98", .token = "SBB B"},    {.code = "99", .token = "SBB C"},
    {.code = "9A", .token = "SBB D"},    {.code = "9B", .token = "SBB E"},
    {.code = "9C", .token = "SBB H"},    {.code = "9D", .token = "SBB L"},
    {.code = "9E", .token = "SBB M"},    {.code = "9F", .token = "SBB A"},
    {.code = "A0", .token = "ANA B"},    {.code = "A1", .token = "ANA C"},
    {.code = "A2", .token = "ANA D"},    {.code = "A3", .token = "ANA E"},
    {.code = "A4", .token = "ANA H"},    {.code = "A5", .token = "ANA L"},
    {.code = "A6", .token = "ANA M"},    {.code = "A7", .token = "ANA A"},
    {.code = "A8", .token = "XRA B"},    {.code = "A9", .token = "XRA C"},
    {.code = "AA", .token = "XRA D"},    {.code = "AB", .token = "XRA E"},
    {.code = "AC", .token = "XRA H"},    {.code = "AD", .token = "XRA L"},
    {.code = "AE", .token = "XRA M"},    {.code = "AF", .token = "XRA A"},
    {.code = "B0", .token = "ORA B"},    {.code = "B1", .token = "ORA C"},
    {.code = "B2", .token = "ORA D"},    {.code = "B3", .token = "ORA E"},
    {.code = "B4", .token = "ORA H"},    {.code = "B5", .token = "ORA L"},
    {.code = "B6", .token = "ORA M"},    {.code = "B7", .token = "ORA A"},
    {.code = "B8", .token = "CMP B"},    {.code = "B9", .token = "CMP C"},
    {.code = "BA", .token = "CMP D"},    {.code = "BB", .token = "CMP E"},
    {.code = "BC", .token = "CMP H"},    {.code = "BD", .token = "CMP L"},
    {.code = "BE", .token = "CMP M"},    {.code = "BF", .token = "CMP A"},
    {.code = "C0", .token = "RNZ"},      {.code = "C1", .token = "POP B"},
    {.code = "C2", .token = "JNZ"},  {.code = "C3", .token = "JMP"},
    {.code = "C4", .token = "CNZ"},  {.code = "C5", .token = "PUSH B"},
    {.code = "C6", .token = "ADI d8"},   {.code = "C7", .token = "RST 0"},
    {.code = "C8", .token = "RZ"},       {.code = "C9", .token = "RET"},
    {.code = "CA", .token = "JZ"},   {.code = "CB", .token = "*JMP"},
    {.code = "CC", .token = "CZ"},   {.code = "CD", .token = "CALL"},
    {.code = "CE", .token = "ACI d8"},   {.code = "CF", .token = "RST 1"},
    {.code = "D0", .token = "RNC"},      {.code = "D1", .token = "POP D"},
    {.code = "D2", .token = "JNC"},  {.code = "D3", .token = "OUT d8"},
    {.code = "D4", .token = "CNC"},  {.code = "D5", .token = "PUSH D"},
    {.code = "D6", .token = "SUI d8"},   {.code = "D7", .token = "RST 2"},
    {.code = "D8", .token = "RC"},       {.code = "D9", .token = "*RET"},
    {.code = "DA", .token = "JC"},   {.code = "DB", .token = "IN d8"},
    {.code = "DC", .token = "CC"},   {.code = "DD", .token = "*CALL"},
    {.code = "DE", .token = "SBI d8"},   {.code = "DF", .token = "RST 3"},
    {.code = "E0", .token = "RPO"},      {.code = "E1", .token = "POP H"},
    {.code = "E2", .token = "JPO"},  {.code = "E3", .token = "XTHL"},
    {.code = "E4", .token = "CPO"},  {.code = "E5", .token = "PUSH H"},
    {.code = "E6", .token = "ANI d8"},   {.code = "E7", .token = "RST 4"},
    {.code = "E8", .token = "RPE"},      {.code = "E9", .token = "PCHL"},
    {.code = "EA", .token = "JPE"},  {.code = "EB", .token = "XCHG"},
    {.code = "EC", .token = "CPE"},  {.code = "ED", .token = "*CALL"},
    {.code = "EE", .token = "XRI d8"},   {.code = "EF", .token = "RST 5"},
    {.code = "F0", .token = "RP"},       {.code = "F1", .token = "POP PSW"},
    {.code = "F2", .token = "JP"},   {.code = "F3", .token = "DI"},
    {.code = "F4", .token = "CP"},   {.code = "F5", .token = "PUSH PSW"},
    {.code = "F6", .token = "ORI d8"},   {.code = "F7", .token = "RST 6"},
    {.code = "F8", .token = "RM"},       {.code = "F9", .token = "SPHL"},
    {.code = "FA", .token = "JM"},   {.code = "FB", .token = "EI"},
    {.code = "FC", .token = "CM"},   {.code = "FD", .token = "*CALL"},
    {.code = "FE", .token = "CPI d8"},   {.code = "FF", .token = "RST 7"}};