#define NUMBER_OF_INSTRUCTIONS 256

struct Instruction {
  char code[16];
  char mnemonic[16];
  int bytes;
};

struct Instruction INSTRUCTIONS[] = {
    {.code = "00", .mnemonic = "NOP", .bytes = 1},
    {.code = "01", .mnemonic = "LXI B", .bytes = 3},
    {.code = "02", .mnemonic = "STAX B", .bytes = 1},
    {.code = "03", .mnemonic = "INX B", .bytes = 1},
    {.code = "04", .mnemonic = "INR B", .bytes = 1},
    {.code = "05", .mnemonic = "DCR B", .bytes = 1},
    {.code = "06", .mnemonic = "MVI B", .bytes = 2},
    {.code = "07", .mnemonic = "RLC", .bytes = 1},
    {.code = "08", .mnemonic = "*NOP", .bytes = 1},
    {.code = "09", .mnemonic = "DAD B", .bytes = 1},
    {.code = "0A", .mnemonic = "LDAX B", .bytes = 1},
    {.code = "0B", .mnemonic = "DCX B", .bytes = 1},
    {.code = "0C", .mnemonic = "INR C", .bytes = 1},
    {.code = "0D", .mnemonic = "DCR C", .bytes = 1},
    {.code = "0E", .mnemonic = "MVI C", .bytes = 2},
    {.code = "0F", .mnemonic = "RRC", .bytes = 1},
    {.code = "10", .mnemonic = "*NOP", .bytes = 1},
    {.code = "11", .mnemonic = "LXI D", .bytes = 3},
    {.code = "12", .mnemonic = "STAX D", .bytes = 1},
    {.code = "13", .mnemonic = "INX D", .bytes = 1},
    {.code = "14", .mnemonic = "INR D", .bytes = 1},
    {.code = "15", .mnemonic = "DCR D", .bytes = 1},
    {.code = "16", .mnemonic = "MVI D", .bytes = 2},
    {.code = "17", .mnemonic = "RAL", .bytes = 1},
    {.code = "18", .mnemonic = "*NOP", .bytes = 1},
    {.code = "19", .mnemonic = "DAD D", .bytes = 1},
    {.code = "1A", .mnemonic = "LDAX D", .bytes = 1},
    {.code = "1B", .mnemonic = "DCX D", .bytes = 1},
    {.code = "1C", .mnemonic = "INR E", .bytes = 1},
    {.code = "1D", .mnemonic = "DCR E", .bytes = 1},
    {.code = "1E", .mnemonic = "MVI E", .bytes = 2},
    {.code = "1F", .mnemonic = "RAR", .bytes = 1},
    {.code = "20", .mnemonic = "*NOP", .bytes = 1},
    {.code = "21", .mnemonic = "LXI H", .bytes = 3},
    {.code = "22", .mnemonic = "SHLD", .bytes = 3},
    {.code = "23", .mnemonic = "INX H", .bytes = 1},
    {.code = "24", .mnemonic = "INR H", .bytes = 1},
    {.code = "25", .mnemonic = "DCR H", .bytes = 1},
    {.code = "26", .mnemonic = "MVI H", .bytes = 2},
    {.code = "27", .mnemonic = "DAA", .bytes = 1},
    {.code = "28", .mnemonic = "*NOP", .bytes = 1},
    {.code = "29", .mnemonic = "DAD H", .bytes = 1},
    {.code = "2A", .mnemonic = "LHLD", .bytes = 3},
    {.code = "2B", .mnemonic = "DCX H", .bytes = 1},
    {.code = "2C", .mnemonic = "INR L", .bytes = 1},
    {.code = "2D", .mnemonic = "DCR L", .bytes = 1},
    {.code = "2E", .mnemonic = "MVI L", .bytes = 2},
    {.code = "2F", .mnemonic = "CMA", .bytes = 1},
    {.code = "30", .mnemonic = "*NOP", .bytes = 1},
    {.code = "31", .mnemonic = "LXI SP", .bytes = 3},
    {.code = "32", .mnemonic = "STA", .bytes = 3},
    {.code = "33", .mnemonic = "INX SP", .bytes = 1},
    {.code = "34", .mnemonic = "INR M", .bytes = 1},
    {.code = "35", .mnemonic = "DCR M", .bytes = 1},
    {.code = "36", .mnemonic = "MVI M", .bytes = 2},
    {.code = "37", .mnemonic = "STC", .bytes = 1},
    {.code = "38", .mnemonic = "*NOP", .bytes = 1},
    {.code = "39", .mnemonic = "DAD SP", .bytes = 1},
    {.code = "3A", .mnemonic = "LDA", .bytes = 3},
    {.code = "3B", .mnemonic = "DCX SP", .bytes = 1},
    {.code = "3C", .mnemonic = "INR A", .bytes = 1},
    {.code = "3D", .mnemonic = "DCR A", .bytes = 1},
    {.code = "3E", .mnemonic = "MVI A", .bytes = 2},
    {.code = "3F", .mnemonic = "CMC", .bytes = 1},
    {.code = "40", .mnemonic = "MOV B,B", .bytes = 1},
    {.code = "41", .mnemonic = "MOV B,C", .bytes = 1},
    {.code = "42", .mnemonic = "MOV B,D", .bytes = 1},
    {.code = "43", .mnemonic = "MOV B,E", .bytes = 1},
    {.code = "44", .mnemonic = "MOV B,H", .bytes = 1},
    {.code = "45", .mnemonic = "MOV B,L", .bytes = 1},
    {.code = "46", .mnemonic = "MOV B,M", .bytes = 1},
    {.code = "47", .mnemonic = "MOV B,A", .bytes = 1},
    {.code = "48", .mnemonic = "MOV C,B", .bytes = 1},
    {.code = "49", .mnemonic = "MOV C,C", .bytes = 1},
    {.code = "4A", .mnemonic = "MOV C,D", .bytes = 1},
    {.code = "4B", .mnemonic = "MOV C,E", .bytes = 1},
    {.code = "4C", .mnemonic = "MOV C,H", .bytes = 1},
    {.code = "4D", .mnemonic = "MOV C,L", .bytes = 1},
    {.code = "4E", .mnemonic = "MOV C,M", .bytes = 1},
    {.code = "4F", .mnemonic = "MOV C,A", .bytes = 1},
    {.code = "50", .mnemonic = "MOV D,B", .bytes = 1},
    {.code = "51", .mnemonic = "MOV D,C", .bytes = 1},
    {.code = "52", .mnemonic = "MOV D,D", .bytes = 1},
    {.code = "53", .mnemonic = "MOV D,E", .bytes = 1},
    {.code = "54", .mnemonic = "MOV D,H", .bytes = 1},
    {.code = "55", .mnemonic = "MOV D,L", .bytes = 1},
    {.code = "56", .mnemonic = "MOV D,M", .bytes = 1},
    {.code = "57", .mnemonic = "MOV D,A", .bytes = 1},
    {.code = "58", .mnemonic = "MOV E,B", .bytes = 1},
    {.code = "59", .mnemonic = "MOV E,C", .bytes = 1},
    {.code = "5A", .mnemonic = "MOV E,D", .bytes = 1},
    {.code = "5B", .mnemonic = "MOV E,E", .bytes = 1},
    {.code = "5C", .mnemonic = "MOV E,H", .bytes = 1},
    {.code = "5D", .mnemonic = "MOV E,L", .bytes = 1},
    {.code = "5E", .mnemonic = "MOV E,M", .bytes = 1},
    {.code = "5F", .mnemonic = "MOV E,A", .bytes = 1},
    {.code = "60", .mnemonic = "MOV H,B", .bytes = 1},
    {.code = "61", .mnemonic = "MOV H,C", .bytes = 1},
    {.code = "62", .mnemonic = "MOV H,D", .bytes = 1},
    {.code = "63", .mnemonic = "MOV H,E", .bytes = 1},
    {.code = "64", .mnemonic = "MOV H,H", .bytes = 1},
    {.code = "65", .mnemonic = "MOV H,L", .bytes = 1},
    {.code = "66", .mnemonic = "MOV H,M", .bytes = 1},
    {.code = "67", .mnemonic = "MOV H,A", .bytes = 1},
    {.code = "68", .mnemonic = "MOV L,B", .bytes = 1},
    {.code = "69", .mnemonic = "MOV L,C", .bytes = 1},
    {.code = "6A", .mnemonic = "MOV L,D", .bytes = 1},
    {.code = "6B", .mnemonic = "MOV L,E", .bytes = 1},
    {.code = "6C", .mnemonic = "MOV L,H", .bytes = 1},
    {.code = "6D", .mnemonic = "MOV L,L", .bytes = 1},
    {.code = "6E", .mnemonic = "MOV L,M", .bytes = 1},
    {.code = "6F", .mnemonic = "MOV L,A", .bytes = 1},
    {.code = "70", .mnemonic = "MOV M,B", .bytes = 1},
    {.code = "71", .mnemonic = "MOV M,C", .bytes = 1},
    {.code = "72", .mnemonic = "MOV M,D", .bytes = 1},
    {.code = "73", .mnemonic = "MOV M,E", .bytes = 1},
    {.code = "74", .mnemonic = "MOV M,H", .bytes = 1},
    {.code = "75", .mnemonic = "MOV M,L", .bytes = 1},
    {.code = "76", .mnemonic = "HLT", .bytes = 1},
    {.code = "77", .mnemonic = "MOV M,A", .bytes = 1},
    {.code = "78", .mnemonic = "MOV A,B", .bytes = 1},
    {.code = "79", .mnemonic = "MOV A,C", .bytes = 1},
    {.code = "7A", .mnemonic = "MOV A,D", .bytes = 1},
    {.code = "7B", .mnemonic = "MOV A,E", .bytes = 1},
    {.code = "7C", .mnemonic = "MOV A,H", .bytes = 1},
    {.code = "7D", .mnemonic = "MOV A,L", .bytes = 1},
    {.code = "7E", .mnemonic = "MOV A,M", .bytes = 1},
    {.code = "7F", .mnemonic = "MOV A,A", .bytes = 1},
    {.code = "80", .mnemonic = "ADD B", .bytes = 1},
    {.code = "81", .mnemonic = "ADD C", .bytes = 1},
    {.code = "82", .mnemonic = "ADD D", .bytes = 1},
    {.code = "83", .mnemonic = "ADD E", .bytes = 1},
    {.code = "84", .mnemonic = "ADD H", .bytes = 1},
    {.code = "85", .mnemonic = "ADD L", .bytes = 1},
    {.code = "86", .mnemonic = "ADD M", .bytes = 1},
    {.code = "87", .mnemonic = "ADD A", .bytes = 1},
    {.code = "88", .mnemonic = "ADC B", .bytes = 1},
    {.code = "89", .mnemonic = "ADC C", .bytes = 1},
    {.code = "8A", .mnemonic = "ADC D", .bytes = 1},
    {.code = "8B", .mnemonic = "ADC E", .bytes = 1},
    {.code = "8C", .mnemonic = "ADC H", .bytes = 1},
    {.code = "8D", .mnemonic = "ADC L", .bytes = 1},
    {.code = "8E", .mnemonic = "ADC M", .bytes = 1},
    {.code = "8F", .mnemonic = "ADC A", .bytes = 1},
    {.code = "90", .mnemonic = "SUB B", .bytes = 1},
    {.code = "91", .mnemonic = "SUB C", .bytes = 1},
    {.code = "92", .mnemonic = "SUB D", .bytes = 1},
    {.code = "93", .mnemonic = "SUB E", .bytes = 1},
    {.code = "94", .mnemonic = "SUB H", .bytes = 1},
    {.code = "95", .mnemonic = "SUB L", .bytes = 1},
    {.code = "96", .mnemonic = "SUB M", .bytes = 1},
    {.code = "97", .mnemonic = "SUB A", .bytes = 1},
    {.code = "98", .mnemonic = "SBB B", .bytes = 1},
    {.code = "99", .mnemonic = "SBB C", .bytes = 1},
    {.code = "9A", .mnemonic = "SBB D", .bytes = 1},
    {.code = "9B", .mnemonic = "SBB E", .bytes = 1},
    {.code = "9C", .mnemonic = "SBB H", .bytes = 1},
    {.code = "9D", .mnemonic = "SBB L", .bytes = 1},
    {.code = "9E", .mnemonic = "SBB M", .bytes = 1},
    {.code = "9F", .mnemonic = "SBB A", .bytes = 1},
    {.code = "A0", .mnemonic = "ANA B", .bytes = 1},
    {.code = "A1", .mnemonic = "ANA C", .bytes = 1},
    {.code = "A2", .mnemonic = "ANA D", .bytes = 1},
    {.code = "A3", .mnemonic = "ANA E", .bytes = 1},
    {.code = "A4", .mnemonic = "ANA H", .bytes = 1},
    {.code = "A5", .mnemonic = "ANA L", .bytes = 1},
    {.code = "A6", .mnemonic = "ANA M", .bytes = 1},
    {.code = "A7", .mnemonic = "ANA A", .bytes = 1},
    {.code = "A8", .mnemonic = "XRA B", .bytes = 1},
    {.code = "A9", .mnemonic = "XRA C", .bytes = 1},
    {.code = "AA", .mnemonic = "XRA D", .bytes = 1},
    {.code = "AB", .mnemonic = "XRA E", .bytes = 1},
    {.code = "AC", .mnemonic = "XRA H", .bytes = 1},
    {.code = "AD", .mnemonic = "XRA L", .bytes = 1},
    {.code = "AE", .mnemonic = "XRA M", .bytes = 1},
    {.code = "AF", .mnemonic = "XRA A", .bytes = 1},
    {.code = "B0", .mnemonic = "ORA B", .bytes = 1},
    {.code = "B1", .mnemonic = "ORA C", .bytes = 1},
    {.code = "B2", .mnemonic = "ORA D", .bytes = 1},
    {.code = "B3", .mnemonic = "ORA E", .bytes = 1},
    {.code = "B4", .mnemonic = "ORA H", .bytes = 1},
    {.code = "B5", .mnemonic = "ORA L", .bytes = 1},
    {.code = "B6", .mnemonic = "ORA M", .bytes = 1},
    {.code = "B7", .mnemonic = "ORA A", .bytes = 1},
    {.code = "B8", .mnemonic = "CMP B", .bytes = 1},
    {.code = "B9", .mnemonic = "CMP C", .bytes = 1},
    {.code = "BA", .mnemonic = "CMP D", .bytes = 1},
    {.code = "BB", .mnemonic = "CMP E", .bytes = 1},
    {.code = "BC", .mnemonic = "CMP H", .bytes = 1},
    {.code = "BD", .mnemonic = "CMP L", .bytes = 1},
    {.code = "BE", .mnemonic = "CMP M", .bytes = 1},
    {.code = "BF", .mnemonic = "CMP A", .bytes = 1},
    {.code = "C0", .mnemonic = "RNZ", .bytes = 1},
    {.code = "C1", .mnemonic = "POP B", .bytes = 1},
    {.code = "C2", .mnemonic = "JNZ", .bytes = 3},
    {.code = "C3", .mnemonic = "JMP", .bytes = 3},
    {.code = "C4", .mnemonic = "CNZ", .bytes = 3},
    {.code = "C5", .mnemonic = "PUSH B", .bytes = 1},
    {.code = "C6", .mnemonic = "ADI", .bytes = 2},
    {.code = "C7", .mnemonic = "RST 0", .bytes = 1},
    {.code = "C8", .mnemonic = "RZ", .bytes = 1},
    {.code = "C9", .mnemonic = "RET", .bytes = 1},
    {.code = "CA", .mnemonic = "JZ", .bytes = 3},
    {.code = "CB", .mnemonic = "*JMP", .bytes = 3},
    {.code = "CC", .mnemonic = "CZ", .bytes = 3},
    {.code = "CD", .mnemonic = "CALL", .bytes = 3},
    {.code = "CE", .mnemonic = "ACI", .bytes = 2},
    {.code = "CF", .mnemonic = "RST 1", .bytes = 1},
    {.code = "D0", .mnemonic = "RNC", .bytes = 1},
    {.code = "D1", .mnemonic = "POP D", .bytes = 1},
    {.code = "D2", .mnemonic = "JNC", .bytes = 3},
    {.code = "D3", .mnemonic = "OUT", .bytes = 2},
    {.code = "D4", .mnemonic = "CNC", .bytes = 3},
    {.code = "D5", .mnemonic = "PUSH D", .bytes = 1},
    {.code = "D6", .mnemonic = "SUI", .bytes = 2},
    {.code = "D7", .mnemonic = "RST 2", .bytes = 1},
    {.code = "D8", .mnemonic = "RC", .bytes = 1},
    {.code = "D9", .mnemonic = "*RET", .bytes = 1},
    {.code = "DA", .mnemonic = "JC", .bytes = 3},
    {.code = "DB", .mnemonic = "IN", .bytes = 2},
    {.code = "DC", .mnemonic = "CC", .bytes = 3},
    {.code = "DD", .mnemonic = "*CALL", .bytes = 3},
    {.code = "DE", .mnemonic = "SBI", .bytes = 2},
    {.code = "DF", .mnemonic = "RST 3", .bytes = 1},
    {.code = "E0", .mnemonic = "RPO", .bytes = 1},
    {.code = "E1", .mnemonic = "POP H", .bytes = 1},
    {.code = "E2", .mnemonic = "JPO", .bytes = 3},
    {.code = "E3", .mnemonic = "XTHL", .bytes = 1},
    {.code = "E4", .mnemonic = "CPO", .bytes = 3},
    {.code = "E5", .mnemonic = "PUSH H", .bytes = 1},
    {.code = "E6", .mnemonic = "ANI", .bytes = 2},
    {.code = "E7", .mnemonic = "RST 4", .bytes = 1},
    {.code = "E8", .mnemonic = "RPE", .bytes = 1},
    {.code = "E9", .mnemonic = "PCHL", .bytes = 1},
    {.code = "EA", .mnemonic = "JPE", .bytes = 3},
    {.code = "EB", .mnemonic = "XCHG", .bytes = 1},
    {.code = "EC", .mnemonic = "CPE", .bytes = 3},
    {.code = "ED", .mnemonic = "*CALL", .bytes = 3},
    {.code = "EE", .mnemonic = "XRI", .bytes = 2},
    {.code = "EF", .mnemonic = "RST 5", .bytes = 1},
    {.code = "F0", .mnemonic = "RP", .bytes = 1},
    {.code = "F1", .mnemonic = "POP PSW", .bytes = 1},
    {.code = "F2", .mnemonic = "JP", .bytes = 3},
    {.code = "F3", .mnemonic = "DI", .bytes = 1},
    {.code = "F4", .mnemonic = "CP", .bytes = 3},
    {.code = "F5", .mnemonic = "PUSH PSW", .bytes = 1},
    {.code = "F6", .mnemonic = "ORI", .bytes = 2},
    {.code = "F7", .mnemonic = "RST 6", .bytes = 1},
    {.code = "F8", .mnemonic = "RM", .bytes = 1},
    {.code = "F9", .mnemonic = "SPHL", .bytes = 1},
    {.code = "FA", .mnemonic = "JM", .bytes = 3},
    {.code = "FB", .mnemonic = "EI", .bytes = 1},
    {.code = "FC", .mnemonic = "CM", .bytes = 3},
    {.code = "FD", .mnemonic = "*CALL", .bytes = 3},
    {.code = "FE", .mnemonic = "CPI", .bytes = 2},
    {.code = "FF", .mnemonic = "RST 7", .bytes = 1}};